### ISSUE TITLE
todo: Basic methods

### ISSUE THREAD

**Issue by therealcdaher** [therealcdaher/playlistthing#1]
- [x] convert playlist
- [x] copy files
- [ ] check folder per user-set time variable
- [ ] read config from file and update
- [ ] make everything available through an API call
