### ISSUE TITLE
todo: Config via web GUI

### ISSUE THREAD

**Issue by therealcdaher** [therealcdaher/playlistthing#2]
- [ ] set all relevant variables
- [ ] save to config file accessed by backend
- [ ] push config
- [ ] don't look terrible
